version: '3'
services:
  front:
    build: ./front
    ports:
      - 5713:5713
    networks:
      network:
        ipv4_address: 10.5.0.2
  search:
    build: ./backend/search
    ports:
      - 18811:18811
    volumes:
      - ./data:/app/data
    networks:
      network:
        ipv4_address: 10.5.0.3
  backend:
    build: ./backend/api
    ports:
      - 5000:5000
    volumes:
      - ./api_summorize_config.py:/app/summorize/config.py
    depends_on:
      - search
    networks:
      network:
        ipv4_address: 10.5.0.4

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
